# Generated by Django 5.2.17 on 2026-08-27 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Uso administrativo. O aluno nao ve este campo.', verbose_name='observacoes')),
                ('source', models.CharField(choices=[('MANUAL', 'Cadastro manual'), ('IMPORT', 'Importacao de planilha')], db_index=True, default='MANUAL', max_length=20, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil de aluno',
                'verbose_name_plural': 'perfis de aluno',
                'ordering': ['user__full_name'],
            },
        ),
    ]
