# Generated by Django 5.2.17 on 2026-09-01 03:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0007_points_snapshot_das_tentativas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='codigo de verificacao')),
                ('status', models.CharField(choices=[('ACTIVE', 'Valido'), ('REVOKED', 'Revogado')], db_index=True, default='ACTIVE', max_length=8, verbose_name='situacao')),
                ('student_name_snapshot', models.CharField(max_length=150, verbose_name='nome do aluno')),
                ('module_name_snapshot', models.CharField(max_length=150, verbose_name='nome do modulo')),
                ('exam_title_snapshot', models.CharField(max_length=200, verbose_name='titulo da prova')),
                ('institution_name_snapshot', models.CharField(max_length=150, verbose_name='instituicao')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='emitido em')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='motivo da revogacao')),
                ('template_version', models.PositiveSmallIntegerField(default=1, verbose_name='versao do modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('attempt', models.OneToOneField(help_text='Uma tentativa aprovada gera no maximo um certificado.', on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='exams.examattempt', verbose_name='tentativa')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_revoked', to=settings.AUTH_USER_MODEL, verbose_name='revogado por')),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['status', '-issued_at'], name='certificado_situacao_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'REVOKED'])), name='certificado_situacao_conhecida'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', False), ('status', 'REVOKED')), models.Q(('revoked_at__isnull', True), ('status', 'ACTIVE')), _connector='OR'), name='certificado_revogacao_coerente')],
            },
        ),
    ]
