# Generated by Django 5.2.17 on 2026-09-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_year_snapshot',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ano'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_dates_snapshot',
            field=models.CharField(blank=True, max_length=120, verbose_name='data(s) do curso'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_location_snapshot',
            field=models.CharField(blank=True, max_length=120, verbose_name='local'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_name_snapshot',
            field=models.CharField(blank=True, max_length=200, verbose_name='nome do curso'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='module_display_name_snapshot',
            field=models.CharField(blank=True, max_length=150, verbose_name='modulo no certificado'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signatory_name_snapshot',
            field=models.CharField(blank=True, max_length=150, verbose_name='signatario'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signatory_title_snapshot',
            field=models.CharField(blank=True, max_length=150, verbose_name='cargo do signatario'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='workload_hours_snapshot',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='carga horaria'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='template_version',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='versao do modelo'),
        ),
    ]
