# Generated by Django 5.2.17 on 2026-09-02 15:46

import certificates.models.template
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_modelo_oficial_do_certificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='template_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='configuracao congelada'),
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('ACTIVE', 'Ativo'), ('ARCHIVED', 'Arquivado')], db_index=True, default='DRAFT', max_length=10, verbose_name='situacao')),
                ('is_global', models.BooleanField(default=False, help_text='Usado por qualquer modulo que nao tenha um modelo proprio configurado. So pode existir um ativo.', verbose_name='modelo padrao')),
                ('background', models.FileField(blank=True, help_text='PNG ou JPG da arte oficial, sem os campos variaveis.', upload_to=certificates.models.template.caminho_do_fundo, verbose_name='arte de fundo')),
                ('background_checksum', models.CharField(blank=True, max_length=64, verbose_name='checksum da arte')),
                ('background_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='largura da arte em pixels')),
                ('background_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='altura da arte em pixels')),
                ('page_orientation', models.CharField(choices=[('LANDSCAPE', 'Paisagem'), ('PORTRAIT', 'Retrato')], default='LANDSCAPE', max_length=10, verbose_name='orientacao')),
                ('page_width_mm', models.DecimalField(decimal_places=2, default=297, max_digits=6, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(2000)], verbose_name='largura da pagina em mm')),
                ('page_height_mm', models.DecimalField(decimal_places=2, default=210, max_digits=6, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(2000)], verbose_name='altura da pagina em mm')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_templates_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derivados', to='certificates.certificatetemplate', verbose_name='modelo de origem')),
            ],
            options={
                'verbose_name': 'modelo de certificado',
                'verbose_name_plural': 'modelos de certificado',
                'ordering': ['name', '-version'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.certificatetemplate', verbose_name='modelo utilizado'),
        ),
        migrations.CreateModel(
            name='CertificateTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('STUDENT_NAME', 'Nome do aluno'), ('COURSE_NAME', 'Nome do curso'), ('MODULE_NAME', 'Modulo'), ('COURSE_DATES', 'Data(s) do curso'), ('COURSE_LOCATION', 'Local'), ('WORKLOAD', 'Carga horaria'), ('YEAR', 'Ano'), ('ISSUED_AT', 'Data de emissao'), ('INSTITUTION', 'Instituicao'), ('SIGNATORY_NAME', 'Signatario'), ('SIGNATORY_TITLE', 'Cargo do signatario'), ('VERIFICATION_CODE', 'Codigo de validacao'), ('QR_CODE', 'QR Code'), ('STATIC_IMAGE', 'Imagem fixa')], max_length=24, verbose_name='campo')),
                ('x', models.DecimalField(decimal_places=2, default=10, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='x (%)')),
                ('y', models.DecimalField(decimal_places=2, default=10, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='y (%)')),
                ('width', models.DecimalField(decimal_places=2, default=30, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='largura (%)')),
                ('height', models.DecimalField(decimal_places=2, default=8, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='altura (%)')),
                ('font_family', models.CharField(default='Helvetica', max_length=32, verbose_name='fonte')),
                ('font_size', models.PositiveSmallIntegerField(default=14, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(120)], verbose_name='tamanho')),
                ('min_font_size', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(120)], verbose_name='tamanho minimo')),
                ('auto_fit', models.BooleanField(default=True, help_text='Reduz a fonte ate o texto caber na caixa.', verbose_name='ajustar automaticamente')),
                ('line_height', models.DecimalField(decimal_places=2, default=1.2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.8), django.core.validators.MaxValueValidator(3)], verbose_name='entrelinha')),
                ('text_align', models.CharField(choices=[('LEFT', 'Esquerda'), ('CENTER', 'Centro'), ('RIGHT', 'Direita')], default='CENTER', max_length=8, verbose_name='alinhamento')),
                ('text_color', models.CharField(default='#000000', max_length=7, verbose_name='cor')),
                ('rotation', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)], verbose_name='rotacao')),
                ('image', models.FileField(blank=True, upload_to=certificates.models.template.caminho_do_asset, verbose_name='imagem')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visivel')),
                ('z_index', models.PositiveSmallIntegerField(default=0, help_text='Maior desenha por cima. O fundo esta sempre atras de tudo.', verbose_name='ordem de desenho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='certificates.certificatetemplate', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'campo do modelo',
                'verbose_name_plural': 'campos do modelo',
                'ordering': ['z_index', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='certificatetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('page_width_mm__gt', 0), ('page_height_mm__gt', 0)), name='modelo_pagina_positiva'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='modelo_versao_pelo_menos_um'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACTIVE'), _negated=True), models.Q(('background', ''), _negated=True), _connector='OR'), name='modelo_ativo_tem_arte'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', True), ('status', 'ACTIVE')), fields=('is_global',), name='modelo_global_ativo_unico'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplatefield',
            constraint=models.UniqueConstraint(condition=models.Q(('field_type', 'STATIC_IMAGE'), _negated=True), fields=('template', 'field_type'), name='campo_unico_por_modelo'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplatefield',
            constraint=models.CheckConstraint(condition=models.Q(('x__gte', 0), ('x__lte', 100), ('y__gte', 0), ('y__lte', 100), ('width__gt', 0), ('width__lte', 100), ('height__gt', 0), ('height__lte', 100)), name='campo_dentro_da_pagina'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplatefield',
            constraint=models.CheckConstraint(condition=models.Q(('font_size__gte', 6), ('font_size__lte', 120), ('min_font_size__gte', 6), ('min_font_size__lte', 120)), name='campo_fonte_em_faixa_util'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplatefield',
            constraint=models.CheckConstraint(condition=models.Q(('min_font_size__lte', models.F('font_size'))), name='campo_minimo_nao_passa_do_tamanho'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplatefield',
            constraint=models.CheckConstraint(condition=models.Q(('rotation__gte', -360), ('rotation__lte', 360)), name='campo_rotacao_em_faixa'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplatefield',
            constraint=models.CheckConstraint(condition=models.Q(('text_color__regex', '^#[0-9A-Fa-f]{6}$')), name='campo_cor_hexadecimal'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplatefield',
            constraint=models.CheckConstraint(condition=models.Q(('field_type', 'STATIC_IMAGE'), ('image', ''), _connector='OR'), name='campo_imagem_so_em_imagem_fixa'),
        ),
    ]
