"""
Editor visual: texto personalizado e quebra de linha.

Tres mudancas, todas aditivas. Nenhuma migration anterior foi tocada.

1. content e wrap
   O texto do bloco personalizado e o interruptor da quebra automatica.

2. CUSTOM_TEXT
   Novo valor de field_type.

3. campo_unico_por_modelo passa a excluir CUSTOM_TEXT
   A constraint impedia dois campos do mesmo tipo no mesmo modelo, com
   excecao da imagem fixa. Texto personalizado entra na mesma excecao: dois
   blocos de texto sao o uso normal, um paragrafo no corpo e uma observacao
   no rodape.

   Uma UniqueConstraint com condicao nao e alterada no lugar — o Django a
   remove e recria. E o que estas operacoes fazem, e por isso a remocao
   aparece antes da criacao com o mesmo nome.

A constraint nova, campo_texto_so_em_texto_personalizado, e o par da que ja
existia para a imagem: so o bloco personalizado carrega texto proprio.
"""

# Generated by Django 5.2.17 on 2026-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_data_de_conclusao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificatetemplatefield',
            name='campo_unico_por_modelo',
        ),
        migrations.AddField(
            model_name='certificatetemplatefield',
            name='content',
            field=models.TextField(blank=True, verbose_name='texto'),
        ),
        migrations.AddField(
            model_name='certificatetemplatefield',
            name='wrap',
            field=models.BooleanField(default=True, verbose_name='quebrar linha'),
        ),
        migrations.AlterField(
            model_name='certificatetemplatefield',
            name='field_type',
            field=models.CharField(choices=[('STUDENT_NAME', 'Nome do aluno'), ('COMPLETION_DATE', 'Data de conclusao'), ('COURSE_NAME', 'Nome do curso'), ('MODULE_NAME', 'Modulo'), ('COURSE_DATES', 'Data(s) do curso'), ('COURSE_LOCATION', 'Local'), ('WORKLOAD', 'Carga horaria'), ('YEAR', 'Ano'), ('ISSUED_AT', 'Data de emissao'), ('INSTITUTION', 'Instituicao'), ('SIGNATORY_NAME', 'Signatario'), ('SIGNATORY_TITLE', 'Cargo do signatario'), ('VERIFICATION_CODE', 'Codigo de validacao'), ('QR_CODE', 'QR Code'), ('STATIC_IMAGE', 'Imagem fixa'), ('CUSTOM_TEXT', 'Texto personalizado')], max_length=24, verbose_name='campo'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplatefield',
            constraint=models.UniqueConstraint(condition=models.Q(('field_type__in', ['STATIC_IMAGE', 'CUSTOM_TEXT']), _negated=True), fields=('template', 'field_type'), name='campo_unico_por_modelo'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplatefield',
            constraint=models.CheckConstraint(condition=models.Q(('field_type', 'CUSTOM_TEXT'), ('content', ''), _connector='OR'), name='campo_texto_so_em_texto_personalizado'),
        ),
    ]
