# Generated by Django 5.2.17 on 2026-08-28 17:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('instructions', models.TextField(blank=True, help_text='Texto exibido ao aluno antes de iniciar a prova.', verbose_name='instrucoes')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicada'), ('CLOSED', 'Fechada')], db_index=True, default='DRAFT', max_length=12, verbose_name='situacao')),
                ('open_at', models.DateTimeField(blank=True, help_text='Obrigatorio para publicar.', null=True, verbose_name='abertura')),
                ('close_at', models.DateTimeField(blank=True, help_text='Obrigatorio para publicar. Precisa ser posterior a abertura.', null=True, verbose_name='encerramento')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Tempo de prova em minutos. Obrigatorio para publicar.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='duracao em minutos')),
                ('passing_score', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Na escala de 0 a 10.', max_digits=4, verbose_name='nota minima')),
                ('total_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Congelado na publicacao. Enquanto a prova e rascunho, a tela mostra a soma corrente das questoes ativas.', max_digits=8, verbose_name='total de pontos')),
                ('failure_message', models.TextField(blank=True, default='Infelizmente voce nao atingiu a nota minima necessaria para aprovacao.\n\nProcure a coordenacao para mais informacoes.', verbose_name='mensagem de reprovacao')),
                ('max_attempts', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tentativas permitidas')),
                ('randomize_questions', models.BooleanField(default=False, verbose_name='sortear ordem das questoes')),
                ('randomize_options', models.BooleanField(default=False, verbose_name='sortear ordem das alternativas')),
                ('show_score_after_submission', models.BooleanField(default=True, verbose_name='mostrar nota apos o envio')),
                ('access_password_hash', models.CharField(blank=True, max_length=128, verbose_name='hash da senha de acesso')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicada em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechada em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='courses.module', verbose_name='modulo')),
                ('parent_exam', models.ForeignKey(blank=True, help_text='De qual prova esta versao foi duplicada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivadas', to='exams.exam', verbose_name='prova de origem')),
                ('root_exam', models.ForeignKey(blank=True, help_text='Nulo na primeira versao, que e a propria raiz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes', to='exams.exam', verbose_name='raiz da linhagem')),
            ],
            options={
                'verbose_name': 'prova',
                'verbose_name_plural': 'provas',
                'ordering': ['module__order', 'module__name', 'title', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SINGLE_CHOICE', 'Escolha unica'), ('MULTIPLE_CHOICE', 'Multiplas respostas'), ('TRUE_FALSE', 'Verdadeiro ou falso'), ('SHORT_TEXT', 'Resposta curta'), ('ESSAY', 'Dissertativa')], default='SINGLE_CHOICE', max_length=20, verbose_name='tipo')),
                ('text', models.TextField(verbose_name='enunciado')),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Precisa ser maior que zero.', max_digits=6, verbose_name='valor')),
                ('required', models.BooleanField(default=True, help_text='Questao nao respondida valera zero na correcao.', verbose_name='obrigatoria')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('internal_explanation', models.TextField(blank=True, help_text='Visivel apenas para a equipe administrativa. Nunca e enviada ao aluno.', verbose_name='explicacao interna')),
                ('active', models.BooleanField(default=True, help_text='Questao inativa nao conta na prova nem na soma de pontos.', verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='prova')),
            ],
            options={
                'verbose_name': 'questao',
                'verbose_name_plural': 'questoes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='texto')),
                ('is_correct', models.BooleanField(default=False, help_text='Gabarito. Nunca e enviado ao aluno.', verbose_name='correta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question', verbose_name='questao')),
            ],
            options={
                'verbose_name': 'alternativa',
                'verbose_name_plural': 'alternativas',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['module', 'status'], name='exam_modulo_situacao_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('passing_score__gte', 0), ('passing_score__lte', Decimal('10.00'))), name='exam_nota_minima_entre_0_e_10'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('total_points__gte', 0)), name='exam_total_de_pontos_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='exam_tentativas_pelo_menos_uma'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__isnull', True), ('duration_minutes__gte', 1), _connector='OR'), name='exam_duracao_positiva_quando_definida'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='exam_versao_pelo_menos_um'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('open_at__isnull', True), ('close_at__isnull', True), ('open_at__lt', models.F('close_at')), _connector='OR'), name='exam_janela_coerente'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('root_exam', 'version'), name='exam_versao_unica_na_linhagem'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'order'], name='question_prova_ordem_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('points__gt', 0)), name='question_valor_positivo'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'order'], name='opcao_questao_ordem_idx'),
        ),
    ]
