# Generated by Django 5.2.17 on 2026-08-28 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('root_exam__isnull', True), ('version', 1)), models.Q(('root_exam__isnull', False), ('version__gte', 2)), _connector='OR'), name='exam_raiz_e_versao_coerentes'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent_exam__isnull', True), ('root_exam__isnull', True)), models.Q(('parent_exam__isnull', False), ('root_exam__isnull', False)), _connector='OR'), name='exam_linhagem_parent_coerente'),
        ),
    ]
