# Generated by Django 5.2.17 on 2026-08-28 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_coerencia_da_linhagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='parent_exam',
            field=models.ForeignKey(blank=True, help_text='De qual prova esta versao foi duplicada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derivadas', to='exams.exam', verbose_name='prova de origem'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='root_exam',
            field=models.ForeignKey(blank=True, help_text='Nulo na primeira versao, que e a propria raiz.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='exams.exam', verbose_name='raiz da linhagem'),
        ),
    ]
