# Generated by Django 5.2.17 on 2026-08-28 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_linhagem_protect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token publico')),
                ('display_order', models.PositiveIntegerField(verbose_name='ordem de exibicao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_questions', to='exams.question', verbose_name='questao')),
            ],
            options={
                'verbose_name': 'questao da tentativa',
                'verbose_name_plural': 'questoes da tentativa',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttemptOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token publico')),
                ('display_order', models.PositiveIntegerField(verbose_name='ordem de exibicao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_options', to='exams.questionoption', verbose_name='alternativa')),
                ('attempt_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.attemptquestion', verbose_name='questao da tentativa')),
            ],
            options={
                'verbose_name': 'alternativa da tentativa',
                'verbose_name_plural': 'alternativas da tentativa',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='resposta em texto')),
                ('saved_at', models.DateTimeField(verbose_name='salva em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('attempt_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='exams.attemptquestion', verbose_name='questao da tentativa')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
                'ordering': ['attempt_question__display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador publico')),
                ('attempt_number', models.PositiveIntegerField(help_text='Sequencial por aluno e prova. Nunca reaproveitado.', verbose_name='numero da tentativa')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em andamento'), ('SUBMITTED', 'Enviada'), ('EXPIRED', 'Tempo encerrado'), ('RESET', 'Anulada')], db_index=True, default='IN_PROGRESS', max_length=12, verbose_name='situacao')),
                ('started_at', models.DateTimeField(verbose_name='iniciada em')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='expirada em')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='ultima atividade')),
                ('total_points_snapshot', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='total de pontos na largada')),
                ('passing_score_snapshot', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='nota minima na largada')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereco IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user-agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='exams.exam', verbose_name='prova')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'tentativa',
                'verbose_name_plural': 'tentativas',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.examattempt', verbose_name='tentativa'),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='exams.answer', verbose_name='resposta')),
                ('attempt_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='exams.attemptoption', verbose_name='alternativa da tentativa')),
            ],
            options={
                'verbose_name': 'alternativa marcada',
                'verbose_name_plural': 'alternativas marcadas',
                'ordering': ['attempt_option__display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('answer', 'attempt_option'), name='resposta_alternativa_uma_vez')],
            },
        ),
        migrations.AddConstraint(
            model_name='attemptoption',
            constraint=models.UniqueConstraint(fields=('attempt_question', 'option'), name='tentativa_alternativa_uma_vez'),
        ),
        migrations.AddConstraint(
            model_name='attemptoption',
            constraint=models.UniqueConstraint(fields=('attempt_question', 'display_order'), name='tentativa_alternativa_posicao_unica'),
        ),
        migrations.AddConstraint(
            model_name='attemptoption',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='tentativa_alternativa_posicao_nao_negativa'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'exam'], name='tentativa_aluno_prova_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status', 'expires_at'], name='tentativa_situacao_prazo_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('student', 'exam', 'attempt_number'), name='tentativa_numero_unico_por_aluno_e_prova'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('student', 'exam'), name='uniq_tentativa_em_andamento'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='tentativa_numero_pelo_menos_um'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('started_at'))), name='tentativa_prazo_posterior_ao_inicio'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('total_points_snapshot__gte', 0)), name='tentativa_total_de_pontos_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('passing_score_snapshot__gte', 0), ('passing_score_snapshot__lte', 10)), name='tentativa_nota_minima_entre_0_e_10'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='tentativa_questao_uma_vez'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'display_order'), name='tentativa_posicao_unica'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='tentativa_questao_posicao_nao_negativa'),
        ),
    ]
