# Generated by Django 5.2.17 on 2026-08-31 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_tentativas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expired_at__isnull', True), ('status', 'IN_PROGRESS'), ('submitted_at__isnull', True)), models.Q(('expired_at__isnull', True), ('status', 'SUBMITTED'), ('submitted_at__isnull', False)), models.Q(('expired_at__isnull', False), ('status', 'EXPIRED'), ('submitted_at__isnull', True)), ('status', 'RESET'), _connector='OR'), name='tentativa_status_e_timestamps_coerentes'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('submitted_at__isnull', True), ('submitted_at__gte', models.F('started_at')), _connector='OR'), name='tentativa_envio_nao_anterior_ao_inicio'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('expired_at__isnull', True), ('expired_at__gte', models.F('started_at')), _connector='OR'), name='tentativa_expiracao_nao_anterior_ao_inicio'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['IN_PROGRESS', 'SUBMITTED', 'EXPIRED', 'RESET'])), name='tentativa_situacao_conhecida'),
        ),
    ]
