# Generated by Django 5.2.17 on 2026-08-31 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_coerencia_status_tentativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='awarded_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='pontos concedidos'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='corrigida em'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes_corrigidas', to=settings.AUTH_USER_MODEL, verbose_name='corrigida por'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='grader_comment',
            field=models.TextField(blank=True, verbose_name='comentario do avaliador'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='grading_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('AUTO_GRADED', 'Corrigida automaticamente'), ('MANUALLY_GRADED', 'Corrigida pelo avaliador')], db_index=True, default='PENDING', max_length=16, verbose_name='situacao da correcao'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='points_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='valor da questao na largada'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='nota final'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='corrigida em'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='grading_status',
            field=models.CharField(choices=[('PENDING', 'Aguardando correcao'), ('AWAITING_REVIEW', 'Aguardando avaliador'), ('GRADED', 'Corrigida')], db_index=True, default='PENDING', max_length=16, verbose_name='situacao da correcao'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='manual_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='pontos das manuais'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='objective_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='pontos das objetivas'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='obtained_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='pontos obtidos'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='result',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Aprovado'), ('FAILED', 'Reprovado')], db_index=True, max_length=8, null=True, verbose_name='resultado'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['grading_status', 'submitted_at'], name='tentativa_correcao_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.CheckConstraint(condition=models.Q(('grading_status__in', ['PENDING', 'AUTO_GRADED', 'MANUALLY_GRADED'])), name='tentativa_questao_correcao_conhecida'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.CheckConstraint(condition=models.Q(('awarded_points__isnull', True), ('awarded_points__gte', 0), _connector='OR'), name='tentativa_questao_pontos_nao_negativos'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.CheckConstraint(condition=models.Q(('awarded_points__isnull', True), ('points_snapshot__isnull', True), ('awarded_points__lte', models.F('points_snapshot')), _connector='OR'), name='tentativa_questao_pontos_ate_o_valor'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('awarded_points__isnull', True), ('grading_status', 'PENDING')), models.Q(models.Q(('grading_status', 'PENDING'), _negated=True), ('awarded_points__isnull', False)), _connector='OR'), name='tentativa_questao_pontos_coerentes_com_situacao'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('grading_status__in', ['PENDING', 'AWAITING_REVIEW', 'GRADED'])), name='tentativa_correcao_situacao_conhecida'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('result__isnull', True), ('result__in', ['APPROVED', 'FAILED']), _connector='OR'), name='tentativa_resultado_conhecido'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('final_score__isnull', False), ('graded_at__isnull', False), ('grading_status', 'GRADED'), ('result__isnull', False)), models.Q(models.Q(('grading_status', 'GRADED'), _negated=True), ('final_score__isnull', True), ('graded_at__isnull', True), ('result__isnull', True)), _connector='OR'), name='tentativa_nota_so_existe_se_corrigida'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('objective_points__gte', 0), ('manual_points__gte', 0), ('obtained_points__gte', 0)), name='tentativa_pontos_obtidos_nao_negativos'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('final_score__isnull', True), models.Q(('final_score__gte', 0), ('final_score__lte', 10)), _connector='OR'), name='tentativa_nota_final_entre_0_e_10'),
        ),
    ]
