"""
Campos e constraints da anulacao administrativa de tentativa.

Nenhum dado existente e alterado: as tentativas ja gravadas continuam com
reset_at nulo, que e exatamente o que a constraint de coerencia exige de
quem nao esta com status RESET.
"""

# Generated by Django 5.2.17 on 2026-09-01 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_points_snapshot_das_tentativas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anulada em'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='reset_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts_reset', to=settings.AUTH_USER_MODEL, verbose_name='anulada por'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='reset_reason',
            field=models.TextField(blank=True, help_text='Obrigatorio ao anular. Fica no registro, e nao na auditoria.', max_length=1000, verbose_name='motivo da anulacao'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reset_at__isnull', False), ('status', 'RESET')), models.Q(models.Q(('status', 'RESET'), _negated=True), ('reset_at__isnull', True)), _connector='OR'), name='tentativa_anulacao_coerente'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('reset_at__isnull', True), ('reset_at__gte', models.F('started_at')), _connector='OR'), name='tentativa_anulacao_nao_anterior_ao_inicio'),
        ),
    ]
