# Generated by Django 5.2.17 on 2026-09-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_gestao_operacional'),
        ('exams', '0008_anulacao_de_tentativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='archive_reason',
            field=models.TextField(blank=True, help_text='Obrigatorio ao arquivar. Fica na propria prova.', max_length=1000, verbose_name='motivo do arquivamento'),
        ),
        migrations.AddField(
            model_name='exam',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='arquivada em'),
        ),
        migrations.AddField(
            model_name='exam',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_arquivadas', to=settings.AUTH_USER_MODEL, verbose_name='arquivada por'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Retirada da operacao. Nao altera a situacao historica.', verbose_name='arquivada'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('is_archived', False)), models.Q(('archived_at__isnull', False), ('is_archived', True)), _connector='OR'), name='exam_arquivamento_coerente'),
        ),
    ]
