# Generated by Django 5.2.17 on 2026-08-27 14:55

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('code', models.CharField(error_messages={'unique': 'Ja existe um modulo com este codigo.'}, help_text='Identificador curto, como MOD1. Gravado sempre em maiusculas.', max_length=30, unique=True, verbose_name='codigo')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Modulo inativo nao aparece para o aluno.', verbose_name='ativo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibicao. Menor aparece primeiro.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'modulo',
                'verbose_name_plural': 'modulos',
                'ordering': ['order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='module_ordem_nao_negativa'), models.UniqueConstraint(django.db.models.functions.text.Upper('code'), name='module_codigo_unico_ignorando_caixa')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa'), ('COMPLETED', 'Concluida')], db_index=True, default='ACTIVE', max_length=12, verbose_name='situacao')),
                ('access_enabled', models.BooleanField(default=True, help_text='Bloqueio operacional. Nao altera a situacao academica.', verbose_name='acesso liberado')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='matriculado em')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.module', verbose_name='modulo')),
            ],
            options={
                'verbose_name': 'matricula',
                'verbose_name_plural': 'matriculas',
                'ordering': ['module__order', 'module__name', 'student__full_name'],
                'indexes': [models.Index(fields=['student', 'status'], name='matricula_aluno_situacao_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'module'), name='matricula_unica_por_aluno_e_modulo')],
            },
        ),
    ]
