# Generated by Django 5.2.17 on 2026-09-01 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='certificate_course_dates_text',
            field=models.CharField(blank=True, help_text='Texto livre, exatamente como deve sair impresso. Exemplo: 10 e 17 de outubro de 2026.', max_length=120, verbose_name='data(s) do curso'),
        ),
        migrations.AddField(
            model_name='module',
            name='certificate_display_name',
            field=models.CharField(blank=True, help_text='Como o modulo aparece no documento, por extenso. Exemplo: Modulo I - Cooperadores e Diaconos. Em branco, o certificado usa o nome do modulo.', max_length=150, verbose_name='nome no certificado'),
        ),
        migrations.AddField(
            model_name='module',
            name='certificate_location',
            field=models.CharField(blank=True, help_text='Onde o curso foi realizado. Exemplo: Igreja Sede.', max_length=120, verbose_name='local'),
        ),
        migrations.AddField(
            model_name='module',
            name='certificate_workload_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Em horas, numero inteiro maior que zero.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='carga horaria'),
        ),
        migrations.AddField(
            model_name='module',
            name='certificate_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ano em destaque na lateral do certificado. Exemplo: 2026.', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='ano'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('certificate_workload_hours__isnull', True), ('certificate_workload_hours__gt', 0), _connector='OR'), name='module_carga_horaria_positiva'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('certificate_year__isnull', True), models.Q(('certificate_year__gte', 2000), ('certificate_year__lte', 2100)), _connector='OR'), name='module_ano_do_certificado_plausivel'),
        ),
    ]
