# Generated by Django 5.2.17 on 2026-09-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_modelo_oficial_do_certificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='revocation_reason',
            field=models.TextField(blank=True, help_text='Obrigatorio ao revogar. Fica na propria matricula.', max_length=1000, verbose_name='motivo da revogacao'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='revogada em'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_revogadas', to=settings.AUTH_USER_MODEL, verbose_name='revogada por'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa'), ('COMPLETED', 'Concluida'), ('REVOKED', 'Revogada')], db_index=True, default='ACTIVE', max_length=12, verbose_name='situacao'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', False), ('status', 'REVOKED')), models.Q(models.Q(('status', 'REVOKED'), _negated=True), ('revoked_at__isnull', True)), _connector='OR'), name='matricula_revogacao_coerente'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVOKED'), _negated=True), ('access_enabled', False), _connector='OR'), name='matricula_revogada_sem_acesso'),
        ),
    ]
