# Generated by Django 5.2.17 on 2026-09-02 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_editor_de_modelos'),
        ('courses', '0003_gestao_operacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='certificate_template',
            field=models.ForeignKey(blank=True, help_text='Em branco, o modulo usa o modelo padrao ativo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='certificates.certificatetemplate', verbose_name='modelo de certificado'),
        ),
    ]
