# Generated by Django 5.2.17 on 2026-08-27 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('LOGIN_SUCCESS', 'Login realizado'), ('LOGIN_FAILED', 'Falha de login'), ('PASSWORD_CHANGED', 'Senha alterada')], db_index=True, max_length=64, verbose_name='evento')),
                ('entity_type', models.CharField(blank=True, max_length=64, verbose_name='tipo da entidade')),
                ('entity_id', models.CharField(blank=True, max_length=64, verbose_name='id da entidade')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data e hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereco IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user-agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('actor', models.ForeignKey(blank=True, help_text='Quem executou a acao. Nulo em falha de login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_como_autor', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('student', models.ForeignKey(blank=True, help_text='Aluno afetado, quando a acao recai sobre um aluno.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_como_aluno', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['event', '-timestamp'], name='audit_evento_data_idx'), models.Index(fields=['student', '-timestamp'], name='audit_aluno_data_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_entidade_idx')],
            },
        ),
    ]
