# Generated by Django 5.2.17 on 2026-08-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login realizado'), ('LOGIN_FAILED', 'Falha de login'), ('PASSWORD_CHANGED', 'Senha alterada'), ('STUDENT_CREATED', 'Aluno criado'), ('STUDENT_UPDATED', 'Aluno atualizado'), ('STUDENT_BLOCKED', 'Aluno bloqueado'), ('STUDENT_UNBLOCKED', 'Aluno desbloqueado'), ('STUDENT_IMPORT_COMPLETED', 'Importacao concluida'), ('MODULE_CREATED', 'Modulo criado'), ('MODULE_UPDATED', 'Modulo atualizado'), ('MODULE_ENABLED', 'Modulo ativado'), ('MODULE_DISABLED', 'Modulo desativado'), ('ENROLLMENT_CREATED', 'Matricula criada'), ('ENROLLMENT_REMOVED', 'Matricula desativada'), ('ENROLLMENT_REACTIVATED', 'Matricula reativada'), ('ENROLLMENT_BLOCKED', 'Acesso da matricula bloqueado'), ('ENROLLMENT_UNBLOCKED', 'Acesso da matricula liberado'), ('ENROLLMENT_COMPLETED', 'Matricula concluida')], db_index=True, max_length=64, verbose_name='evento'),
        ),
    ]
