# Generated by Django 5.2.17 on 2026-08-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login realizado'), ('LOGIN_FAILED', 'Falha de login'), ('PASSWORD_CHANGED', 'Senha alterada'), ('STUDENT_CREATED', 'Aluno criado'), ('STUDENT_UPDATED', 'Aluno atualizado'), ('STUDENT_BLOCKED', 'Aluno bloqueado'), ('STUDENT_UNBLOCKED', 'Aluno desbloqueado'), ('STUDENT_IMPORT_COMPLETED', 'Importacao concluida'), ('MODULE_CREATED', 'Modulo criado'), ('MODULE_UPDATED', 'Modulo atualizado'), ('MODULE_ENABLED', 'Modulo ativado'), ('MODULE_DISABLED', 'Modulo desativado'), ('ENROLLMENT_CREATED', 'Matricula criada'), ('ENROLLMENT_REMOVED', 'Matricula desativada'), ('ENROLLMENT_REACTIVATED', 'Matricula reativada'), ('ENROLLMENT_BLOCKED', 'Acesso da matricula bloqueado'), ('ENROLLMENT_UNBLOCKED', 'Acesso da matricula liberado'), ('ENROLLMENT_COMPLETED', 'Matricula concluida'), ('EXAM_CREATED', 'Prova criada'), ('EXAM_UPDATED', 'Prova atualizada'), ('EXAM_PUBLISHED', 'Prova publicada'), ('EXAM_CLOSED', 'Prova fechada'), ('EXAM_DUPLICATED', 'Prova duplicada'), ('EXAM_PASSWORD_CHANGED', 'Senha da prova alterada'), ('EXAM_PASSWORD_REMOVED', 'Senha da prova removida'), ('QUESTION_CREATED', 'Questao criada'), ('QUESTION_UPDATED', 'Questao atualizada'), ('QUESTION_DELETED', 'Questao excluida'), ('ATTEMPT_STARTED', 'Tentativa iniciada'), ('ATTEMPT_SUBMITTED', 'Tentativa enviada'), ('ATTEMPT_EXPIRED', 'Tentativa expirada')], db_index=True, max_length=64, verbose_name='evento'),
        ),
    ]
